// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npiaytgwvqepwdtlyidy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5waWF5dGd3dnFlcHdkdGx5aWR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzODM4ODQsImV4cCI6MjA3MDk1OTg4NH0.XGKie2Xz-NbEHTY2GdFZaFIU4xfP2IX0PQyAeUx7E8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});